version: '3'
services:
  mysql-todo-apps:
    container_name: mysql-todo-apps
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
       - 'MYSQL_RANDOM_ROOT_PASSWORD=yes'
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
